# -----------------------------------------------------------------------------
# Visionary Cross Project – Jekyll Configuration
# -----------------------------------------------------------------------------

# Site Identity
title: Visionary Cross Project 3.0
email: jocelyn.mcknight@uleth.ca
description: >-
  Visionary Cross is a multimedia edition and archive—a critical edition, scholarly study,
  and textual archive of the Old English Visionary Cross Tradition. The Visionary Cross Project
  is an international, multidisciplinary research initiative focused on creating a new kind
  of digital archive and edition of texts and objects associated with the Visionary Cross tradition
  in Anglo-Saxon England.

  ISTI-CNR collaborated with project partners in two main activities: the acquisition and processing
  of 3D representations of two important stone crosses (Ruthwell and Bewcastle), and the creation
  of a web-accessible "digital edition" of the Cross, available to both the general public and scholars.

footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a>
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

# Languages and Branding
lang: en
icon: ico.jpg # Add this image to your assets for favicon
baseurl: "" # e.g., /project if deployed under a subpath
url: ""     # e.g., https://yourdomain.com
back_to_top: true

# Display settings
navbar_fixed: true
footer_fixed: true
search_enabled: true

# Layout
max_width: 930px

# -----------------------------------------------------------------------------
# Theme and Plugins
# -----------------------------------------------------------------------------

theme: minima
plugins:
  - jekyll-feed

# -----------------------------------------------------------------------------
# Analytics & Verification
# -----------------------------------------------------------------------------

google_analytics: # add your measurement ID (e.g. G-XXXXXXX)
enable_google_analytics: true

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_darkmode: true
enable_masonry: false
enable_math: true
enable_medium_zoom: true

# -----------------------------------------------------------------------------
# Exclude/Include
# -----------------------------------------------------------------------------

# Add any files or folders you'd like Jekyll to ignore
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock

# Files/folders to explicitly include
# include:
#   - _pages
#   - _data

# -----------------------------------------------------------------------------
# Future Enhancements (Uncomment to use)
# -----------------------------------------------------------------------------
# serve_og_meta: true
# og_image: /assets/img/preview.jpg
# collections:
#   projects:
#     output: true
#     permalink: /:collection/:title/
# markdown: kramdown
# highlighter: rouge
# kramdown:
#   input: GFM

